import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { UserContextProvider } from "@/lib/UserContext";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-100 grainy">
      <head>
      <Script src="https://cdn.intake-lr.com/LogRocket.min.js" crossOrigin="anonymous"></Script>
      <Script>window.LogRocket && window.LogRocket.init('irkulq/coachbots');</Script>
      <Script>window.LogRocket && window.user && window.LogRocket.identify(window.user.email);</Script>
      </head>
      
      <UserContextProvider>
        <body className={inter.className} suppressHydrationWarning>
          <>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <div className="deep-chat-poc"></div>
              <div className="deep-chat-poc2"></div>
              {children}
            </ThemeProvider>
          </>
        </body>
      </UserContextProvider>
    </html>
  );
}
