"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { UserContextProvider } from "@/lib/UserContext";
import Script from "next/script";
import Widgets from "@/components/Widgets";
import { useRouter } from "next/router";
import { usePathname } from "next/navigation";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en" className="bg-gray-100 grainy">
      <Head>
        <script
          src="https://cdn.intake-lr.com/LogRocket.min.js"
          crossOrigin="anonymous"
        ></script>
        <script>
          window.LogRocket && window.LogRocket.init('irkulq/coachbots');
        </script>
        <script>
          window.LogRocket && window.user &&
          window.LogRocket.identify(window.user.email);
        </script>
      </Head>

      <UserContextProvider>
        <body className={inter.className} suppressHydrationWarning={true}>
          <>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <div className="deep-chat-poc"></div>
              <div className="deep-chat-poc2"></div>
              {children}
            </ThemeProvider>
          </>
          {pathname === "/profile" ? null : <Widgets />}
        </body>
      </UserContextProvider>
    </html>
  );
}
